### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by armandzwan** [peterringset/CoreDataCodable#3]
Thank you for your repository, it is helping me to transition from EasyMapping to Codable.
I bumped into an issue and made a fix.

Do you accept pull requests on this repo?

**Comment by peterringset** [comment]
Sure, just send me a pull request and I’ll review it! :)

**Comment by armandzwan** [comment]
Thank you, see #4 .

**Comment by peterringset** [comment]
Merged :)
